const JOKES = [
  // One-liners
  "I told my wife she was drawing her eyebrows too high. She looked surprised.",
  "I'm reading a book about anti-gravity. It's impossible to put down.",
  "I used to hate facial hair, but then it grew on me.",
  "I told my computer I needed a break, and now it won't stop sending me Kit-Kat ads.",
  "Parallel lines have so much in common. It's a shame they'll never meet.",
  "I threw a boomerang a few years ago. I now live in constant fear.",
  "I have a joke about chemistry, but I don't think it will get a reaction.",
  "I'm on a whiskey diet. I've lost three days already.",
  "What's the difference between a hippo and a Zippo? One is really heavy, the other is a little lighter.",
  "I broke my finger last week. On the other hand, I'm okay.",

  // Tech jokes
  "A QA engineer walks into a bar. Orders 1 beer. Orders 0 beers. Orders 99999999 beers. Orders -1 beers. Orders a lizard. Orders NULL beers.",
  "Why do programmers prefer dark mode? Because light attracts bugs.",
  "There are only 10 types of people in the world: those who understand binary and those who don't.",
  "A SQL query walks into a bar, sees two tables, and asks… 'Can I JOIN you?'",
  "Why do Java developers wear glasses? Because they can't C#.",
  "How many programmers does it take to change a light bulb? None. That's a hardware problem.",
  "!false — it's funny because it's true.",
  "A programmer's wife tells him: 'Go to the store and buy a loaf of bread. If they have eggs, buy a dozen.' He comes home with 12 loaves of bread.",
  "Why was the JavaScript developer sad? Because he didn't Node how to Express himself.",
  "Git commit -m 'fixed bug' — narrator: he did not fix the bug.",
  "There's no place like 127.0.0.1.",
  "Algorithm: a word used by programmers when they don't want to explain what they did.",
  "I would tell you a UDP joke, but you might not get it.",
  "TCP joke: Would you like to hear a TCP joke? Yes, I'd like to hear a TCP joke. OK, I'll tell you a TCP joke. OK, I'll hear a TCP joke. OK, here's a TCP joke. OK, I'm ready to hear a TCP joke...",
  "My code doesn't have bugs. It has random features.",
  "The cloud is just someone else's computer having a panic attack.",
  "Debugging is like being the detective in a crime movie where you're also the murderer.",
  "I asked ChatGPT to write my resignation letter. It apologized for any confusion and offered to help me stay.",
  "Recruiter: 'We need someone with 10 years of Kubernetes experience.' Kubernetes: *released 8 years ago*",
  "My code works perfectly. I have no idea why.",

  // Trading/Finance jokes
  "My portfolio is like my dating life — full of red flags I chose to ignore.",
  "I told my financial advisor I wanted to make a killing in the market. He said 'Sir, this is a Wendy's.'",
  "What's the difference between a bond and a bond trader? A bond matures.",
  "Bulls make money, bears make money, pigs get slaughtered. I'm apparently a pigeon — I just make a mess everywhere.",
  "I put my life savings into crypto. Now I have enough for a small coffee. At home.",
  "The stock market is the only place where people panic when things go on sale.",
  "My trading strategy: buy high, sell low, cry in the shower, repeat.",
  "What do you call a trader who's always right? Retired.",
  "I don't always check my portfolio, but when I do, I wish I hadn't.",
  "Investor tip: if you can't afford to lose it, you definitely will.",
  "NFTs taught me that you can sell nothing to someone for everything.",
  "My financial plan is to marry rich, but my portfolio is scaring off the candidates.",
  "The market can stay irrational longer than you can stay solvent — and it knows it.",
  "I diversified my portfolio: I now lose money in multiple asset classes simultaneously.",
  "Day trading is just astrology for men who think they're too smart for astrology.",
  "I bought the dip. Then the dip dipped. Then the dip's dip dipped.",
  "My stop loss triggered. My stop loss has better boundaries than I do.",
  "Quant trading: turning math PhDs into people who lose money faster.",
  "My algorithm has a 90% win rate in backtesting. In production, it has a 90% rate of making me cry.",
  "Options trading is just gambling with extra steps and a Bloomberg terminal.",

  // Dark humor
  "I have a fish that can breakdance. Only for 20 seconds though, and only once.",
  "I asked the librarian if the library had any books about paranoia. She whispered, 'They're right behind you.'",
  "My therapist says I have a preoccupation with vengeance. We'll see about that.",
  "I told my wife I was going to make a bike out of spaghetti. She didn't believe me. You should've seen her face when I rode pasta.",
  "The doctor said I had type A blood, but it was a type O.",
  "I have an inferiority complex, but it's not a very good one.",
  "My wife told me to stop impersonating a flamingo. I had to put my foot down.",
  "I asked my date to meet me at the gym. She didn't show up. I guess the two of us aren't going to work out.",
  "I stayed up all night wondering where the sun went. Then it dawned on me.",
  "My boss told me to have a good day. So I went home.",

  // Dad jokes
  "What do you call a fake noodle? An impasta.",
  "I'm afraid for the calendar. Its days are numbered.",
  "Why don't scientists trust atoms? Because they make up everything.",
  "What did the ocean say to the beach? Nothing, it just waved.",
  "Why did the scarecrow win an award? He was outstanding in his field.",
  "I only know 25 letters of the alphabet. I don't know y.",
  "What do you call a bear with no teeth? A gummy bear.",
  "I used to play piano by ear, but now I use my hands.",
  "What do you call a dog that does magic tricks? A Labracadabrador.",
  "I told my son I was named after Thomas Jefferson. He said, 'But dad, your name is Brian.' I said, 'I know, but I was named AFTER Thomas Jefferson.'",
  "Why don't eggs tell jokes? They'd crack each other up.",
  "I got fired from the calendar factory. All I did was take a day off.",
  "What do you call a sleeping dinosaur? A dino-snore.",
  "Why can't a bicycle stand on its own? It's two tired.",
  "What did the grape do when it got stepped on? Nothing, it just let out a little wine.",

  // Puns
  "Time flies like an arrow. Fruit flies like a banana.",
  "I'm friends with 25 letters of the alphabet. I don't know Y.",
  "A plateau is the highest form of flattery.",
  "Velcro — what a rip-off.",
  "I did a theatrical performance about puns. It was a play on words.",
  "England has no kidney bank, but it does have a Liverpool.",
  "Broken pencils are pointless.",
  "I tried to catch fog yesterday. Mist.",
  "I used to be a banker, but I lost interest.",
  "The rotation of Earth really makes my day.",
  "I was going to tell a time-traveling joke, but you guys didn't like it.",
  "I'm reading a book about teleportation. It's bound to take me places.",
  "The guy who invented autocorrect has died. His funfair is next Monkey.",
  "RIP boiling water. You will be mist.",
  "What's the best thing about Switzerland? I don't know, but the flag is a big plus.",

  // More tech/quant crossover
  "Machine learning is just statistics wearing a Silicon Valley hoodie.",
  "My neural network finally converged. On the wrong answer.",
  "I trained a model to predict the stock market. It predicted I'd lose money. First correct prediction.",
  "Overfitting: when your model memorizes the exam but fails the real test — just like me in college.",
  "The only thing my trading bot prints consistently is error logs.",
  "I use Monte Carlo simulations to decide where to eat lunch. Still end up at the same place.",
  "My Sharpe ratio is so low, even my mom won't invest in my fund.",
  "I told my quant friend a joke about mean reversion. He said 'give it time, it'll get funnier.'",
  "Why did the data scientist break up with the statistician? There was no significant relationship.",
  "I don't always test my code, but when I do, I do it in production.",

  // Extra zingers
  "My internet is so slow, it's buffering this joke.",
  "I finally got eight hours of sleep. Took me three days, but still.",
  "If at first you don't succeed, skydiving is not for you.",
  "I'm not lazy, I'm on energy-saving mode.",
  "My wallet is like an onion. Opening it makes me cry.",
  "I childproofed my house but the kids still got in.",
  "I told my suitcase we weren't going on vacation. Now I'm dealing with emotional baggage.",
  "I was addicted to the hokey pokey, but I turned myself around.",
  "The man who invented knock-knock jokes deserves a no bell prize.",
  "I couldn't figure out how the seat belt worked. Then it clicked.",
  "I'm so good at sleeping I can do it with my eyes closed.",
  "My friend said he didn't understand cloning. I said that makes two of us.",
  "What's a pirate's favorite letter? You'd think it's R, but it's the C.",
  "I went to a seafood disco last week. I pulled a mussel.",
  "The first rule of Passive Aggressive Club is: you know what, never mind.",
];
